/**
 * Export session as markdown
 */

import { existsSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { initDb, getSummaries, getRecentSessions, getSessionTokenStats, GUARD_DIR } from '../lib/db.js';

export async function exportSession(args) {
  await initDb();
  const options = parseArgs(args);

  // Find session
  let session;
  const recentSessions = await getRecentSessions(100);

  if (options.session) {
    session = recentSessions.find(s => s.id.startsWith(options.session));
  } else {
    // Get most recent session
    session = recentSessions[0];
  }

  if (!session) {
    console.log('내보낼 세션이 없습니다');
    return;
  }

  // Generate markdown
  const md = await generateMarkdown(session, options.name);

  // Determine output path
  let outputDir;
  if (options.here) {
    outputDir = join(process.cwd(), '.claude-guard', 'exports');
  } else {
    outputDir = join(GUARD_DIR, 'exports');
  }

  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const filename = options.name
    ? `${sanitizeFilename(options.name)}.md`
    : `${new Date(session.started_at).toISOString().split('T')[0]}_${session.id.slice(0, 8)}.md`;

  const outputPath = join(outputDir, filename);
  writeFileSync(outputPath, md);

  console.log(`내보내기 완료: ${outputPath}`);
}

function parseArgs(args) {
  const options = {};

  for (const arg of args) {
    if (arg.startsWith('--session=')) {
      options.session = arg.split('=')[1];
    } else if (arg.startsWith('--name=')) {
      options.name = arg.split('=')[1];
    } else if (arg === '--here') {
      options.here = true;
    }
  }

  return options;
}

function sanitizeFilename(name) {
  return name.replace(/[^a-zA-Z0-9가-힣_-]/g, '_');
}

async function generateMarkdown(session, customName) {
  const summaries = await getSummaries(session.id);
  const tokens = await getSessionTokenStats(session.id);

  const projectName = session.project_path?.split(/[/\\]/).pop() || 'Unknown Project';

  // Generate title from first summary or custom name
  let title = customName;
  if (!title && summaries.length > 0) {
    const firstSummary = summaries[0]?.summary || '';
    // Clean up summary for title
    title = firstSummary
      .replace(/^(Read |Modified |Created |Ran: |Searched |최종: )/, '')
      .split(/[/\\]/).pop()  // Get filename if path
      .slice(0, 50);
    if (title) {
      title = `${projectName}: ${title}`;
    }
  }
  if (!title) {
    title = `세션: ${projectName}`;
  }

  let md = `# ${title}\n\n`;

  // Metadata
  md += `- **세션 ID**: \`${session.id}\`\n`;
  md += `- **프로젝트**: \`${session.project_path || 'N/A'}\`\n`;
  md += `- **상태**: ${session.status}\n`;
  md += `- **시작**: ${new Date(session.started_at).toLocaleString()}\n`;
  md += `- **총 턴**: ${session.total_turns}\n`;
  md += `- **총 토큰**: ${(tokens.total_input + tokens.total_output).toLocaleString()} (input: ${tokens.total_input.toLocaleString()} / output: ${tokens.total_output.toLocaleString()})\n`;
  md += `\n---\n\n`;

  // Work flow
  md += `## 작업 흐름\n\n`;

  if (summaries.length === 0) {
    md += `_기록된 요약 없음_\n\n`;
  } else {
    for (const s of summaries) {
      const filesRead = JSON.parse(s.files_read || '[]');
      const filesModified = JSON.parse(s.files_modified || '[]');

      md += `### Turn ${s.turn_start}-${s.turn_end}\n\n`;
      md += `${s.summary}\n\n`;

      if (filesRead.length > 0) {
        md += `- **읽음**: ${filesRead.map(f => `\`${f.split(/[/\\]/).pop()}\``).join(', ')}\n`;
      }
      if (filesModified.length > 0) {
        md += `- **수정함**: ${filesModified.map(f => `\`${f.split(/[/\\]/).pop()}\``).join(', ')}\n`;
      }
      md += `- **토큰**: ${s.tokens_used.toLocaleString()}\n\n`;
    }
  }

  // Files summary
  const allFilesModified = new Set();

  for (const s of summaries) {
    const fm = JSON.parse(s.files_modified || '[]');
    fm.forEach(f => allFilesModified.add(f));
  }

  if (allFilesModified.size > 0) {
    md += `---\n\n## 수정된 파일\n\n`;
    for (const f of allFilesModified) {
      md += `- \`${f}\`\n`;
    }
    md += `\n`;
  }

  // Token breakdown
  md += `---\n\n## 토큰 사용량\n\n`;
  md += `| 항목 | 값 |\n`;
  md += `|------|----|\n`;
  md += `| Input 토큰 | ${tokens.total_input.toLocaleString()} |\n`;
  md += `| Output 토큰 | ${tokens.total_output.toLocaleString()} |\n`;
  md += `| 총 토큰 | ${(tokens.total_input + tokens.total_output).toLocaleString()} |\n`;
  md += `\n`;

  // Footer
  md += `---\n\n_Generated by claude-guard_\n`;

  return md;
}
