/**
 * Export session as markdown
 */

import { existsSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { db, getSummaries } from '../lib/db.js';
import { getTokenUsage } from '../lib/session.js';

export async function exportSession(args) {
  const options = parseArgs(args);

  // Find session
  let session;
  if (options.session) {
    session = db.prepare('SELECT * FROM sessions WHERE id LIKE ?').get(`${options.session}%`);
  } else {
    // Get most recent session
    session = db.prepare('SELECT * FROM sessions ORDER BY started_at DESC LIMIT 1').get();
  }

  if (!session) {
    console.log('No session found to export');
    return;
  }

  // Generate markdown
  const md = generateMarkdown(session, options.name);

  // Determine output path
  let outputDir;
  if (options.here) {
    outputDir = join(process.cwd(), '.claude-guard', 'exports');
  } else {
    const { GUARD_DIR } = await import('../lib/db.js');
    outputDir = join(GUARD_DIR, 'exports');
  }

  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const filename = options.name
    ? `${sanitizeFilename(options.name)}.md`
    : `${new Date(session.started_at).toISOString().split('T')[0]}_${session.id.slice(0, 8)}.md`;

  const outputPath = join(outputDir, filename);
  writeFileSync(outputPath, md);

  console.log(`Exported: ${outputPath}`);
}

function parseArgs(args) {
  const options = {};

  for (const arg of args) {
    if (arg.startsWith('--session=')) {
      options.session = arg.split('=')[1];
    } else if (arg.startsWith('--name=')) {
      options.name = arg.split('=')[1];
    } else if (arg === '--here') {
      options.here = true;
    }
  }

  return options;
}

function sanitizeFilename(name) {
  return name.replace(/[^a-zA-Z0-9가-힣_-]/g, '_');
}

function generateMarkdown(session, customName) {
  const summaries = getSummaries(session.id);
  const tokens = getTokenUsage(session.id);

  const projectName = session.project_path?.split(/[/\\]/).pop() || 'Unknown Project';
  const title = customName || `Session: ${projectName}`;

  let md = `# ${title}\n\n`;

  // Metadata
  md += `- **Session ID**: \`${session.id}\`\n`;
  md += `- **Project**: \`${session.project_path || 'N/A'}\`\n`;
  md += `- **Status**: ${session.status}\n`;
  md += `- **Started**: ${new Date(session.started_at).toLocaleString()}\n`;
  if (session.ended_at) {
    md += `- **Ended**: ${new Date(session.ended_at).toLocaleString()}\n`;
  }
  md += `- **Total Turns**: ${session.total_turns}\n`;
  md += `- **Total Tokens**: ${(tokens.total_input + tokens.total_output).toLocaleString()} (input: ${tokens.total_input.toLocaleString()} / output: ${tokens.total_output.toLocaleString()})\n`;
  md += `\n---\n\n`;

  // Work flow
  md += `## Work Flow\n\n`;

  if (summaries.length === 0) {
    md += `_No summaries recorded_\n\n`;
  } else {
    for (const s of summaries) {
      const filesRead = JSON.parse(s.files_read || '[]');
      const filesModified = JSON.parse(s.files_modified || '[]');

      md += `### Turn ${s.turn_start}-${s.turn_end}\n\n`;
      md += `${s.summary}\n\n`;

      if (filesRead.length > 0) {
        md += `- **Read**: ${filesRead.map(f => `\`${f.split(/[/\\]/).pop()}\``).join(', ')}\n`;
      }
      if (filesModified.length > 0) {
        md += `- **Modified**: ${filesModified.map(f => `\`${f.split(/[/\\]/).pop()}\``).join(', ')}\n`;
      }
      md += `- **Tokens**: ${s.tokens_used.toLocaleString()}\n\n`;
    }
  }

  // Files summary
  const allFilesRead = new Set();
  const allFilesModified = new Set();

  for (const s of summaries) {
    const fr = JSON.parse(s.files_read || '[]');
    const fm = JSON.parse(s.files_modified || '[]');
    fr.forEach(f => allFilesRead.add(f));
    fm.forEach(f => allFilesModified.add(f));
  }

  if (allFilesModified.size > 0) {
    md += `---\n\n## Modified Files\n\n`;
    for (const f of allFilesModified) {
      md += `- \`${f}\`\n`;
    }
    md += `\n`;
  }

  // Token breakdown
  md += `---\n\n## Token Usage\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Input Tokens | ${tokens.total_input.toLocaleString()} |\n`;
  md += `| Output Tokens | ${tokens.total_output.toLocaleString()} |\n`;
  md += `| Total Tokens | ${(tokens.total_input + tokens.total_output).toLocaleString()} |\n`;
  md += `\n`;

  // Footer
  md += `---\n\n_Generated by claude-guard_\n`;

  return md;
}
