/**
 * Export session as markdown
 */

import { existsSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { getSummaries, getRecentSessions, getSessionTokenStats, GUARD_DIR } from '../lib/db.js';

export function exportSession(args) {
  const options = parseArgs(args);

  // Find session
  const recentSessions = getRecentSessions(100);
  let session;

  if (options.session) {
    session = recentSessions.find(s => s.id.startsWith(options.session));
  } else {
    session = recentSessions[0];
  }

  if (!session) {
    console.log('내보낼 세션이 없습니다');
    return;
  }

  // Generate markdown
  const md = generateMarkdown(session, options.name);

  // Determine output path
  let outputDir = options.here
    ? join(process.cwd(), '.claude-guard', 'exports')
    : join(GUARD_DIR, 'exports');

  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const filename = options.name
    ? `${sanitizeFilename(options.name)}.md`
    : `${new Date(session.started_at).toISOString().split('T')[0]}_${session.id.slice(0, 8)}.md`;

  const outputPath = join(outputDir, filename);
  writeFileSync(outputPath, md);

  console.log(`내보내기 완료: ${outputPath}`);
}

function parseArgs(args) {
  const options = {};
  for (const arg of args) {
    if (arg.startsWith('--session=')) options.session = arg.split('=')[1];
    else if (arg.startsWith('--name=')) options.name = arg.split('=')[1];
    else if (arg === '--here') options.here = true;
  }
  return options;
}

function sanitizeFilename(name) {
  return name.replace(/[^a-zA-Z0-9가-힣_-]/g, '_');
}

function generateMarkdown(session, customName) {
  const summaries = getSummaries(session.id);
  const tokens = getSessionTokenStats(session.id);
  const projectName = session.project_path?.split(/[/\\]/).pop() || 'Unknown';

  // Generate title
  let title = customName;
  if (!title && summaries.length > 0) {
    title = `${projectName}: ${summaries[0]?.summary?.slice(0, 50) || 'Session'}`;
  }
  if (!title) title = `세션: ${projectName}`;

  let md = `# ${title}\n\n`;

  // Metadata
  md += `- **세션 ID**: \`${session.id}\`\n`;
  md += `- **프로젝트**: \`${session.project_path || 'N/A'}\`\n`;
  md += `- **상태**: ${session.status}\n`;
  md += `- **시작**: ${new Date(session.started_at).toLocaleString()}\n`;
  md += `- **토큰**: ${(tokens.total_input + tokens.total_output).toLocaleString()}\n`;
  md += `\n---\n\n`;

  // Summaries
  md += `## 작업 흐름\n\n`;
  if (summaries.length === 0) {
    md += `_기록된 요약 없음_\n\n`;
  } else {
    for (const s of summaries) {
      md += `- ${s.summary || 'N/A'}`;
      if (s.tokens) md += ` (${(s.tokens.input || 0) + (s.tokens.output || 0)} tokens)`;
      md += `\n`;
    }
  }

  // Token summary
  md += `\n---\n\n## 토큰 사용량\n\n`;
  md += `- Input: ${tokens.total_input.toLocaleString()}\n`;
  md += `- Output: ${tokens.total_output.toLocaleString()}\n`;
  md += `- Total: ${(tokens.total_input + tokens.total_output).toLocaleString()}\n`;

  md += `\n---\n\n_Generated by claude-guard_\n`;

  return md;
}
